### ISSUE TITLE
React App Reader Cursor Throws Error

### ISSUE THREAD

**Issue by orozcojd** [LibertyDSNP/parquetjs#110]
### Steps to reproduce
Containerize React Application with installed parquetjs dependency, use Dockerfile below:

Version Info:
React Scripts: 5.0.1
Node: 16.14.2
@dsnp/parquetjs: 1.3.5

package.json build: `react-scripts build`

```
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY package.json ./package.json
RUN npm cache clean --force && npm install --legacy-peer-deps

COPY . ./

RUN npm run build
FROM nginx:1.21.1-alpine

COPY --from=build /usr/src/app/build /usr/share/nginx/html


RUN rm /etc/nginx/conf.d/default.conf
COPY deploy/nginx/nginx.conf /etc/nginx/conf.d
COPY docker-entrypoint.sh generate-config-js.sh /

EXPOSE 80
CMD ["/docker-entrypoint.sh"]
```

### Expected behaviour
In the containerized React application, the code snippet below at line `getCursor`, throws the error below:

### Actual behaviour
reader.getCursor should not throw an error.

### Any logs, error output, etc?
Code:
```
import parquetjs from "@dsnp/parquetjs/dist/browser/parquet.esm";
const buffer = Buffer.from(arrayData[1], "base64");
const reader = await parquetjs.ParquetReader.openBuffer(buffer);
const cursor = reader.getCursor();
```

Stacktrace:
```
helper.ts:478 TypeError: Cannot read properties of null (reading 'includes')
    at new e (parquet.esm.js:78:21246)
    at e.openEnvelopeReader (parquet.esm.js:78:22667)
    at async helper.ts:463:13
    at async Promise.all (:8080/index 0)
```

```
// parquet.esm.js
!nP.includes(t.version))throw"invalid parquet version"
```

Variable nP is null and script is trying to read includes attribute. 

### Any other comments?
Running my React application with the React dev server, no issues arise. Versions of libraries between local environment and Containerized environments are matching: Node, @dsnp/parquetjs.

What I have tried:
* Disabled minification in the product build using the react-app-rewired library
** Compared the diff between the parquet.esm.js files in production file and the node_modules file (they are equal, no name mangling)
* Tried various import statements: `*.esm, *.cjs`
* Copied the parquet.esm file into my project, instead of import form node_modules and produced production build

**Comment by wilwade** [comment]
@orozcojd Would it be possible for you to share a simplified parquet file this happens with?

It appears that for some reason when it reads the parquet file, it is unable to read the footer (where the metadata is stored) in the production build you have.

The error should have occurred before the error you got, but it apparently did not.

**Comment by orozcojd** [comment]
I wanted to provide an update. After trying different build configuration, it turned out the cached Docker image was the issue. After clearing Docker cache and rebuilding the image, the issue went away.
