### ISSUE TITLE
Project can only be default-imported using the 'esModuleInterop' flag

### ISSUE THREAD

**Issue by sean-legitscript** [LibertyDSNP/parquetjs#124]
Thanks for reporting an issue!

### Steps to reproduce
- Typescript: 4.0.3
- Node: 20
- Use tsconfig.json without esModuleInterop flag set to true.

### Expected behaviour
Should be able to install the package without issue.

### Actual behaviour
When compiling typescript project, I get many errors related to:

node_modules/@dsnp/parquetjs/dist/lib/bloom/sbbf.d.ts(2,8): error TS1259: Module '"/project/node_modules/@types/long/index"' can only be default-imported using the 'esModuleInterop' flag

### Any other comments?
Enabling the esModuleInterop flag will require an import overhaul of my project. Is there any way to utilize this package without the requirement of setting the interop flag to true?

**Comment by wilwade** [comment]
@sean-legitscript Could you post or link to your tsconfig.json?

I was able to get it to work locally, but you might have a different config.

Also I'm not sure, but the issue might be with TypeScript v4 as well.

**Comment by wilwade** [comment]
Stale
