### ISSUE TITLE
BrowserFS Deprecated

### ISSUE THREAD

**Issue by james-pre** [LibertyDSNP/parquetjs#127]
Hi there, I'm the maintainer of BrowserFS. I've been going through the dependents of browserfs.

Please see the notice in the readme: https://github.com/jvilk/browserfs

Would you be interested in updating your project to use the updated fork, [ZenFS](https://github.com/zen-fs/core)?

**Comment by wilwade** [comment]
Thanks @dr-vortex! I think that sounds reasonable and add it to the todo list!

**Comment by james-pre** [comment]
@wilwade I've updated my GitHub username from @dr-vortex to @james-pre. Please update your comment, and I can delete this one. I'm writing this comment when I can't make the change myself.
