### ISSUE TITLE
appendRow is overwriting existing parquet

### ISSUE THREAD

**Issue by suchal** [LibertyDSNP/parquetjs#129]
Thanks for reporting an issue!

### Steps to reproduce
``` 
    var schema = new parquet.ParquetSchema({
      timestamp: parquet.ParquetFieldBuilder.createTimestampField(),
    });
var writer = await parquet.ParquetWriter.openFile(schema, filename);
    await writer.appendRow({
      timestamp: new Date(),
    });
    await writer.close();
```

### Expected behaviour
Adds a new row to the existing file `filename`

### Actual behaviour
Replaces existing data with the new row

### Any logs, error output, etc?
...

### Any other comments?
Apologies if I'm doing something wrong and thanks for maintaining this package.

**Comment by wilwade** [comment]
@suchal As far as I know, this is due to how Parquet files work. When you open a writer to a file, it is just reading the schema and starting a new file.

To append data, you must rewrite the data from the prior rows first.
