### ISSUE TITLE
Statistics = true on a schema type "BYTE_ARRAY" with UInt8Array value throws exception

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/parquetjs#23]
If you have type "BYTE_ARRAY" in your schema and that field contains UInt8Array data, then when parquetjs goes to write the header statistics on `close`, the statistics data is wrong. It attempts to call "copy" on a UInt8Array, expecting a Buffer type.

To reproduce:
* Create a schema with a field of type "BYTE_ARRAY"
* Add a row to the parquet file using UInt8Array data
* Call parquetjs.close()
* Should throw the error.

Note: Check the other forks of Parquetjs that might have a fix for this.

**Comment by wilwade** [comment]
https://github.com/LibertyDSNP/parquetjs/blob/main/lib/writer.js#L362

That function (later down the path) assumes that anything that is BYTE_ARRAY is already a Buffer.
But that's not true. It is also allowed to be a typed array
Typed arrays however are not supported by parquet_thrift
