### ISSUE TITLE
Upstreaming some typescript types

### ISSUE THREAD

**Issue by eatonphil** [LibertyDSNP/parquetjs#25]
I have typescript types for this package in my project https://github.com/multiprocessio/datastation/blob/master/type-overrides/dsnp__parquetjs.d.ts. I'd rather if they were upstreamed though.

Making this issue to discuss you including a .d.ts file with this repo so others don't have to type it. If you are not interested maybe I'll try to upstream it into the @types repo.

**Comment by wilwade** [comment]
Hi @eatonphil 

We're working on adding in a full type definition file, but I don't know if it is going to happen until early next year.

So yes we are interested in adding it, but are not sure we want to just add a partial. (I've had trouble with a few projects that tried to do it progressively).

I know that's not quite the best answer, but we will be trying.

**Comment by wilwade** [comment]
@eatonphil We've got a path to fixing up all the types! https://github.com/LibertyDSNP/parquetjs/milestone/1

**Comment by wilwade** [comment]
@eatonphil and others, just an update that progress has accelerated and we are nearing the release with types. Expected by the end of the month.

**Comment by wilwade** [comment]
Released v1.2.0 🎉 

https://github.com/LibertyDSNP/parquetjs/releases/tag/v1.2.0
