### ISSUE TITLE
Converstion to Full TypeScript

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/parquetjs#26]
An issue to track progress and notes on converting all the remaining JS files to TypeScript.

- Document the list of things to convert
- Document the chunks that are reasonable to convert in
- Document a general estimate of time to convert

When done this would trigger the ability to close #25 by just building the .d.ts files and including them in the package.

**Comment by sidke** [comment]
# parquet typescriptification

## things to convert

- `/`
  - `esbuild-*` (2)
    - optional, but good to make everything consistently in ts
  - `examples/` (2)
  - `lib/`
    - `compression` (1)
    - `codec/` (3)
    - `types/` (2)
      - can improve the `ParquetTypeKit` type and remove all the anys
    - `reader.js` (3)
    - `writer.js` (3)
    - everything else (2)

## chunks

### required, in order

1. independent files
   - `/lib/bufferReader`
   - `/lib/codec`
   - `/lib/compression`
   - `/lib/types`
1. utility
   - `/lib/util`
   - `/lib/schema`
   - `/lib/shred`
   - `/lib/compression`
1. reader/writer
   - `/lib/reader`
   - `/lib/writer`

### optional

- `/esbuild-*`
- `/examples/`

## general estimate

about 3 days for the meat of the work in `lib/` +/- 2 days

**Comment by wilwade** [comment]
Added those chunks as issues at to a Milestone: https://github.com/LibertyDSNP/parquetjs/milestone/1
