### ISSUE TITLE
Util.ts - fixedTFramedTransport

### ISSUE THREAD

**Issue by waylandli** [LibertyDSNP/parquetjs#41]
The current version of thrift within util.js has issues with readString. The later patches of thrift do not have this issue and could allow us to remove the fixedTFramedTransport class altogether. Below are the fixes to thrift

https://github.com/apache/thrift/blob/master/CHANGES.md#092
https://issues.apache.org/jira/browse/THRIFT-1841

**Comment by wilwade** [comment]
Closed with #46
