### ISSUE TITLE
Util.ts - force32

### ISSUE THREAD

**Issue by waylandli** [LibertyDSNP/parquetjs#43]
Don't merge until after: #31 

We currently have a function `force32` that forces 64bit numbers into 32bit. This is dangerous because we want parquetjs to handle 64 bit numbers. We should look into removing this function.

Review https://github.com/LibertyDSNP/parquetjs/commit/a15d62d01e3641114f3079f109532058a56ec56a which is where it was added.

To Do:
- [x] Remove exported function`force32`

**Comment by aramikm** [comment]
I do not see any usage of force32 function, should we just remove it?
