### ISSUE TITLE
Not working in the browser

### ISSUE THREAD

**Issue by plotka** [LibertyDSNP/parquetjs#70]
### Steps to reproduce
Install package and import into a client-side app (react & typescript) like mentioned in the instructions:
`import parquetjs from '@dsnp/parquetjs/browser/parquetjs';`

### Expected behaviour
Should be possible to use the `parquetjs` instance and all the methods, for example `parquetjs.ParquetReader...`

### Actual behaviour
FIrst, there's the import error
```
Cannot find module '@dsnp/parquetjs/browser/parquetjs' or its corresponding type declarations.ts(2307)
```
Then, I tried to import it as:
`import parquetjs from '@dsnp/parquetjs/dist/browser/parquet';
`
and the import error is gone but when I try to use it like this
```js
const reader = await parquetjs.ParquetReader.openBuffer(fileDataBuffer);
```
 there's this error
```js
TypeError: _dsnp_parquetjs_dist_browser_parquet__WEBPACK_IMPORTED_MODULE_1___default().ParquetReader is undefined
```

 How can I make it work in the browser?

**Comment by wilwade** [comment]
@plotka Check out `v1.2.1` and let me know if that solves your problem.

Also note that you will want to switch to this import line (see updated readme for more details):
```javascript
import parquetjs from '@dsnp/parquetjs/dist/browser/parquet.esm';
```

**Comment by wilwade** [comment]
Closing assumed fixed. Please reopen if it is still broken.
