### ISSUE TITLE
Reading snappy compressed files doesn't seem to work in browser

### ISSUE THREAD

**Issue by Kaiido** [LibertyDSNP/parquetjs#72]
### Steps to reproduce

Try to read a parquet file with SNAPPY compression, e.g this one: 
[Sample - Superstore(2018)-snappy.parquet.zip](https://github.com/LibertyDSNP/parquetjs/files/8988838/Sample.-.Superstore.2018.-snappy.parquet.zip)

### Expected behaviour
SNAPPY is supposed to be supported, and so we're supposed to be able to read it from the browser to.

### Actual behaviour
An error is thrown and `cursor.next()` rejects.

### Any logs, error output, etc?
> TypeError: e.buffer.readInt32LE is not a function
    at MR (parquet.esm.js:77:35149)
    at Object.QR (parquet.esm.js:77:37481)
    at Tn (parquet.esm.js:77:63515)
    at rD (parquet.esm.js:77:66120)
    at async sb (parquet.esm.js:77:64215)
    at async fb (parquet.esm.js:77:64733)
    at async Cr.readRowGroup (parquet.esm.js:77:62318)
    at async Ry.next (parquet.esm.js:77:54940)

### Any other comments?
The fix seems actually quite simple, I replaced

https://github.com/LibertyDSNP/parquetjs/blob/a2cd4ff1ee9eac70b45cb292c5d3d2f3178867ff/lib/browser/compression.js#L63

With 
```js
    return Buffer.from(snappy.uncompress(value));
```
And it seems to work.

I don't open a PR yet because I must admit I'm not 100% sure I did include Buffer the right way in my front-end code: I did link to a browserified version of feross's Buffer from my own page, since passing an ArrayBuffer was complaining that I didn't pass a correct parquet file, is it how it's supposed to be done? Sounds quite unfortunate we have to load this Buffer package twice. (Actually 4 times since it's also in bson and browserfs).  
Also I couldn't find unit-tests for this particular script (compression.js), so I'm not sure if this change breaks anything else, and I didn't check either if deflate requires the same treatment, I don't do write in my project yet.

**Comment by JasonYeMSFT** [comment]
I think this is a bug in parquetjs. If snappyjs is expected to return ArrayBuffer or Uint8Array from uncompress, parquetjs should not assume the returned object has the Node buffer APIs.

**Comment by wilwade** [comment]
Verified Closed by #88
