### ISSUE TITLE
Support Frequency Parquet Schema Model Helper Function

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/parquetjs#73]
As a user of Frequency, it would be nice if Parquetjs had a helper function that took in the Parquet Schema Model data and initialized a ParquetWriter from it.

Data Model in Frequency: https://github.com/LibertyDSNP/frequency/blob/main/common/primitives/src/parquet.rs#L21
Example Schema Conversion helper function: https://github.com/LibertyDSNP/schemas/blob/main/helpers/parquet.ts#L22

- [ ] Infer `ParquetSchema` from row data
- [ ] Construct empty `ParquetEnvelopeWriter`
- [ ] Return `ParquetWriter` with all default options

**Comment by mehtaishita** [comment]
@wilwade quick clarification: are we inferring `ParquetSchema` from row data or from `ParquetModel (vec<parquetColumn>)` ?

**Comment by wilwade** [comment]
> are we inferring `ParquetSchema` from row data or from `ParquetModel (vec<parquetColumn>)` ?

I'm not 100% sure I understand, but I think the answer is that `ParquetSchema` in parquetjs is generated from the information provided by the Schema from Frequency which is `ParquetModel (vec<parquetColumn>)`.

**Comment by saraswatpuneet** [comment]
From @rlaferla  https://www.tabnine.com/code/java/classes/org.apache.parquet.hadoop.ParquetWriter

**Comment by saraswatpuneet** [comment]
Questions:
* Is it a generic write for frequency support parquet types or schema specific

**Comment by shannonwells** [comment]
This story is a little bit confusing given your reply to Ish. It sounded almost like the story is to create a ParquetWriter after reading in a parquet file (and we're not sure why one would want to do that), whereas in the follow-up comment, it sounds more like the story is to create a ParquetWriter from Schema data pulled from Frequency.

**Comment by wilwade** [comment]
This is now available through: https://www.npmjs.com/package/@dsnp/frequency-schemas

GitHub: https://github.com/LibertyDSNP/schemas/
