### ISSUE TITLE
Snippet: Generate parquet schema

### ISSUE THREAD

**Issue by noxify** [LibertyDSNP/parquetjs#80]
Hey guys,

we're currently integrating the parquetjs package into our datalake-graphql-wrapper to provide the functionality to upload data in our data lake via graphql.

After some try&error we were able to generate a parquet file which can used in the trino cluster.

Not sure if someone else had already this problem or a solution.. anyway... here our helper functions + example.

```ts
// License Apache-2
// helpers/parquet.ts

import { FieldDefinition, ParquetType } from '@dsnp/parquetjs/dist/lib/declare'

export function createStringField({
  optional = true,
}: Partial<{
  optional: boolean
}>): Partial<FieldDefinition> {
  return createField({ type: 'UTF8', optional })
}

export function createBooleanField({
  optional = true,
}: {
  optional: boolean
}): Partial<FieldDefinition> {
  return createField({ type: 'BOOLEAN', optional })
}

export function createIntField({
  optional = true,
}: {
  optional?: boolean
}): Partial<FieldDefinition> {
  return createField({ type: 'INT64', optional })
}

export function createFloatField({
  optional = true,
}: Partial<{
  optional: boolean
}>): Partial<FieldDefinition> {
  return createField({ type: 'FLOAT', optional })
}

export function createDecimalField({
  precision = 3,
  optional = true,
}: Partial<{
  precision?: number
  optional?: boolean
}>): Partial<FieldDefinition> {
  return createField({ type: 'DECIMAL', precision, optional })
}

export function createTimestampField({
  optional = true,
}: Partial<{
  optional?: boolean
}>) {
  return createField({ type: 'TIMESTAMP_MILLIS', optional })
}

export function createRepeatableStructField({
  fields,
}: {
  fields: { [fieldName: string]: FieldDefinition }
}): Partial<FieldDefinition> {
  return {
    optional: true,
    type: 'LIST',
    fields: {
      list: {
        optional: false,
        repeated: true,
        fields: {
          element: {
            optional: true,
            repeated: false,
            fields: fields,
          },
        },
      },
    },
  }
}

export function createStructField({
  fields,
}: {
  fields: { [fieldName: string]: FieldDefinition }
}): Partial<FieldDefinition> {
  return {
    optional: true,
    fields: fields,
  }
}

export function createArrayField({
  type,
  optional = true,
}: Partial<{
  type: ParquetType
  optional?: boolean
}>): Partial<FieldDefinition> {
  return createField({
    optional,
    type: 'LIST',
    fields: {
      list: {
        optional: false,
        repeated: true,
        fields: {
          element: {
            type,
            optional: true,
          },
        },
      },
    },
  })
}

export function createField(
  definition: FieldDefinition,
): Partial<FieldDefinition> {
  return definition
}
```

And here a "short" example:

```ts
// License Apache-2

import path from 'path'
import parquetjs from '@dsnp/parquetjs'
import {
  createArrayField,
  createFloatField,
  createIntField,
  createRepeatableStructField,
  createStringField,
  createStructField,
  createTimestampField,
} from './helpers/parquet'

const examplePath = path.resolve('test_parquet.parquet')

const parquetSchema = new parquetjs.ParquetSchema({
  stringfield: createStringField({}),
  intfield: createIntField({}),
  floatfield: createFloatField({}),
  timestampfield: createTimestampField({}),
  arrayfield: createArrayField({ type: 'UTF8' }),

  objfield: createStructField({
    fields: {
      sub1: createStringField({}),
      sub2: createStringField({}),
    },
  }),

  structfield: createRepeatableStructField({
    fields: {
      structfield_array: createArrayField({ type: 'UTF8' }),
      structfield_string: createStringField({}),
      structfield_struct: createStructField({
        fields: {
          structfield_struct_string1: createStringField({}),
          structfield_struct_string2: createStringField({}),
        },
      }),
    },
  }),
})

const writer = await parquetjs.ParquetWriter.openFile(
  parquetSchema,
  examplePath,
)

await writer.appendRow({
  stringfield: 'string value',
  intfield: 10,
  floatfield: 10.5,
  timestampfield: new Date(),

  arrayfield: {
    list: [{ element: 'arrayfield val1' }, { element: 'arrayfield val2' }],
  },

  objfield: {
    sub1: 'objfield_sub1 val',
    sub2: 'objfield_sub2 val',
  },

  structfield: {
    list: [
      {
        element: {
          structfield_array: {
            list: [{ element: 'val1' }, { element: 'val2' }],
          },
          structfield_string: 'structfield_string val',
          structfield_struct: {
            structfield_struct_string1: 'structfield_struct_string1 val',
            structfield_struct_string2: 'structfield_struct_string2 val',
          },
        },
      },
    ],
  },
})

await writer.close()

const example_df = await parquetjs.ParquetReader.openFile(examplePath)

console.log(JSON.stringify(example_df.schema.schema, null, 2))

```

Hope that helps you as it helps us :)

**Comment by wilwade** [comment]
@noxify Those examples worked for me!

I've got a backlog item to have a standard way to write a portable schema #73 

This will be helpful to expanding that some to support more use cases. I like how you have little default helpers for the different types. Makes it easy to build up a schema.

**Comment by noxify** [comment]
The list is not complete but these are our main types, but I will update this post if we create new helper

I tried it also with a repeatable structure inside a repeatable structure but it seems they are not supported in Trino or I missed something.

I have checked then our other parquets/hive tables and realized that we have no need (currently) to support this - maybe in the future 🤷🏾‍♂️

P.S. If you think the helper could be useful in this package, feel free to copy&paste them into the library.

**Comment by noxify** [comment]
Hey @wilwade, 

I was able to create some new functionality which allows you:

1. to generate a ParquetSchema based on a given JSON-Schema
2. to convert a given user input in the required `appendRow` format

Could this be helpful, too?

**Comment by wilwade** [comment]
@noxify That sounds great. I think next week I'll have some time to incorporate some helpers along with #73 into a PR, so feel free to drop any code you think might be helpful and I can pull it into that work. Or if you prefer, feel free to open a PR. Either way, thanks for the help!

**Comment by noxify** [comment]
Hi @wilwade ,

i have created a Gist: https://gist.github.com/noxify/9b9d933ac742937a6360366851da97cf 

With this code ( and a lot more e.g. to generate the create table statement) I was able to create an standardized way to provide an mutation endpoint with minimal manual interaction.

* We have a small script which generates the boilerplate based on a template
* We only have to define the json-schema
* We only have to define the interfaces and some definitions for the graphql schema

all other stuff is generated based on the json-schema definition.

If something isn't working, please let me know and I will provide a working example.

**Comment by wilwade** [comment]
@noxify 

I have pulled together a PR generally based on your code. If you have a minute, it'd be great to have you take a look at it: https://github.com/LibertyDSNP/parquetjs/pull/82

**Comment by noxify** [comment]
I close this issue since we integrated the snippet into the package via #82 .

Related docs:
* https://github.com/LibertyDSNP/parquetjs#helper-functions
* https://github.com/LibertyDSNP/parquetjs#json-schema
