### ISSUE TITLE
Support for Parquet file versions above v1?

### ISSUE THREAD

**Issue by jruales** [LibertyDSNP/parquetjs#89]
### Steps to reproduce
Try to open a Parquet file with version other than v1

### Expected behaviour
It should open

### Actual behaviour
Error `invalid parquet version`

### Any other comments?
https://github.com/LibertyDSNP/parquetjs/blob/17cb5ed3533f72f199e6683cc9842935ff07595a/lib/reader.ts#LL24C1-L27C27
https://github.com/LibertyDSNP/parquetjs/blob/17cb5ed3533f72f199e6683cc9842935ff07595a/lib/reader.ts#LL169C1-L171C6

**Comment by wilwade** [comment]
@jruales Should be fixed in https://github.com/LibertyDSNP/parquetjs/releases/tag/v1.3.1 Feel free to reopen if it does not.
